import { quoteArg } from "@agent-master/tmux";

export function shellQuote(value: string): string {
  return `'${value.replace(/'/g, `'\\''`)}'`;
}

/** A tmux config double-quoted string: no $VAR expansion, backslash escapes only. */
export const tmuxQuote = quoteArg;

/** tmux key names such as a, M-a, C-x, F5. */
export const KEY_PATTERN = /^(?:[CMS]-)*[A-Za-z0-9]{1,6}$/;

export function renderTmuxConfig(options: { key: string; node: string; cli: string; opencode: string }): string {
  const { key, node, cli, opencode } = options;
  if (!KEY_PATTERN.test(key)) throw new Error(`--key 不是有效的 tmux 键名：${key}`);
  const command = `exec ${shellQuote(node)} --disable-warning=ExperimentalWarning ${shellQuote(cli)} popup`;
  return [
    "# Generated by `am-ask tmux-install`; re-run it if the repository moves.",
    `bind-key ${key} display-popup -E -w 80% -h 40% -T " shell-ask " -e ${tmuxQuote(`AM_OPENCODE_BIN=${opencode}`)} ${tmuxQuote(command)}`,
    "",
  ].join("\n");
}
