import { execFile } from "node:child_process";
import { lstat, mkdir, readFile, readlink, symlink, unlink, writeFile } from "node:fs/promises";
import { homedir } from "node:os";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const BIN = fileURLToPath(new URL("../bin/am", import.meta.url));
const GUIDE = fileURLToPath(new URL("../skills/am/GUIDE.md", import.meta.url));

const DESCRIPTION =
  "Coordinate other coding agents (Claude Code, Codex, opencode) in tmux panes with the am CLI: start a helper, hand it a task, wait for it, read its reply.";

/** First line of every generated file; only files carrying it are ever overwritten or removed. */
const MARKER = "generated by `am install`";

export interface GeneratedFile {
  path: string;
  content: string;
}

// The guide is opt-in everywhere: each agent only gets it when the user invokes
// it explicitly (/am in Claude Code and opencode, $am in Codex).
export function renderTargets(guide: string, roots: { claude: string; codex: string; opencode: string }): GeneratedFile[] {
  const body = (request: string) => guide.replace("{{REQUEST}}", request).trim();
  const withArgs = body(" Their request: $ARGUMENTS");
  return [
    {
      // A command, not a skill directory: opencode also loads .claude/skills and ignores disable-model-invocation.
      path: join(roots.claude, "commands", "am.md"),
      content: `---\ndescription: ${JSON.stringify(DESCRIPTION)}\nargument-hint: <what to delegate>\ndisable-model-invocation: true\n---\n<!-- ${MARKER} -->\n\n${withArgs}\n`,
    },
    {
      path: join(roots.codex, "am", "SKILL.md"),
      content: `---\nname: am\ndescription: ${JSON.stringify(DESCRIPTION)}\n---\n<!-- ${MARKER} -->\n\n${body(" Their request is the message that invoked this skill.")}\n`,
    },
    {
      // Codex reads SKILL.md frontmatter keys name/description only; explicit-only lives here.
      path: join(roots.codex, "am", "agents", "openai.yaml"),
      content: `# ${MARKER}\npolicy:\n  allow_implicit_invocation: false\n`,
    },
    {
      path: join(roots.opencode, "commands", "am.md"),
      content: `---\ndescription: ${JSON.stringify(DESCRIPTION)}\n---\n<!-- ${MARKER} -->\n\n${withArgs}\n`,
    },
  ];
}

export function globalRoots() {
  const home = homedir();
  return {
    claude: join(home, ".claude"),
    // ~/.codex/skills rather than ~/.agents/skills: opencode scans the latter and would offer it to its model.
    codex: join(process.env.CODEX_HOME ?? join(home, ".codex"), "skills"),
    opencode: join(process.env.XDG_CONFIG_HOME ?? join(home, ".config"), "opencode"),
  };
}

export function projectRoots(dir: string) {
  return { claude: join(dir, ".claude"), codex: join(dir, ".agents", "skills"), opencode: join(dir, ".opencode") };
}

async function exists(path: string): Promise<boolean> {
  return lstat(path).then(
    () => true,
    () => false,
  );
}

async function ownedByUs(path: string): Promise<boolean> {
  return (await readFile(path, "utf8").catch(() => "")).includes(MARKER);
}

async function writeGenerated(files: GeneratedFile[], report: string[]): Promise<void> {
  for (const { path, content } of files) {
    if ((await exists(path)) && !(await ownedByUs(path))) {
      report.push(`skipped ${path} (an existing file not generated by am)`);
      continue;
    }
    if ((await readFile(path, "utf8").catch(() => undefined)) === content) {
      report.push(`up to date: ${path}`);
      continue;
    }
    await mkdir(dirname(path), { recursive: true });
    await writeFile(path, content);
    report.push(`wrote ${path}`);
  }
}

/**
 * Whether a new terminal finds `command`. Checked in a clean login shell: the
 * PATH `am install` itself runs with (inside an agent, say) may not be the user's.
 */
function newTerminalFinds(command: string): Promise<boolean> {
  const shell = process.env.SHELL || "/bin/sh";
  const env = [`HOME=${homedir()}`, `USER=${process.env.USER ?? ""}`, "TERM=dumb", `SHELL=${shell}`];
  return new Promise((resolve) => {
    execFile("/usr/bin/env", ["-i", ...env, shell, "-lic", `command -v ${command} >/dev/null`], { timeout: 15_000 }, (error) => resolve(!error));
  });
}

export async function installGlobal(): Promise<string[]> {
  const report: string[] = [];
  const binLink = join(homedir(), ".local", "bin", "am");
  if (!(await exists(binLink))) {
    await mkdir(dirname(binLink), { recursive: true });
    await symlink(BIN, binLink);
    report.push(`linked ${binLink} → ${BIN}`);
  } else {
    report.push((await readlink(binLink).catch(() => undefined)) === BIN ? `already linked: ${binLink}` : `skipped ${binLink} (taken by another file)`);
  }
  if (!(await newTerminalFinds("am"))) {
    report.push(`warning: a new terminal cannot find am because ${dirname(binLink)} is not on PATH. Add this line to the end of your shell config (e.g. ~/.zshrc): export PATH="$PATH:$HOME/.local/bin"`);
  }
  await writeGenerated(renderTargets(await readFile(GUIDE, "utf8"), globalRoots()), report);
  report.push("Invoke it with /am <task to delegate> in Claude Code and opencode, and $am <task to delegate> in Codex");
  return report;
}

/** opencode also loads .agents/skills, so a project opts its am skill out of opencode's model. */
export const OPENCODE_PROJECT_CONFIG = `${JSON.stringify({ $schema: "https://opencode.ai/config.json", permission: { skill: { am: "deny" } } }, null, 2)}\n`;

/** OpenCode's Wildcard.match (packages/opencode/src/util/wildcard.ts), including its trailing " *" rule. */
function wildcard(pattern: string, value: string): boolean {
  let escaped = pattern
    .replaceAll("\\", "/")
    .replace(/[.+^${}()|[\]\\]/g, "\\$&")
    .replace(/\*/g, ".*")
    .replace(/\?/g, ".");
  // "ls *" matches both "ls" and "ls -la".
  if (escaped.endsWith(" .*")) escaped = `${escaped.slice(0, -3)}( .*)?`;
  return new RegExp(`^${escaped}$`, "s").test(value.replaceAll("\\", "/"));
}

/** The action a rule (string, or object of patterns) gives `name`; the last matching pattern wins (config order, as OpenCode's evaluate()). */
function ruleAction(rule: unknown, name: string): string | undefined {
  if (typeof rule === "string") return rule;
  let action: string | undefined;
  if (rule && typeof rule === "object") {
    for (const [pattern, value] of Object.entries(rule)) if (typeof value === "string" && wildcard(pattern, name)) action = value;
  }
  return action;
}

/**
 * Whether an opencode.json keeps the am skill away from opencode's model:
 * the effective `skill` permission for "am" under opencode's rules (last
 * matching rule wins, top-level "*" included). Unparseable (e.g. JSONC) counts as no.
 */
export function opencodeDeniesAm(configText: string): boolean {
  let permission: unknown;
  try {
    permission = JSON.parse(configText)?.permission;
  } catch {
    return false;
  }
  let action: string | undefined;
  if (typeof permission === "string") action = permission;
  else if (permission && typeof permission === "object") {
    for (const [key, rule] of Object.entries(permission)) {
      if (!wildcard(key, "skill")) continue;
      action = ruleAction(rule, "am") ?? action;
    }
  }
  return action === "deny";
}

export async function installProject(dir: string): Promise<string[]> {
  const report: string[] = [];
  await writeGenerated(renderTargets(await readFile(GUIDE, "utf8"), projectRoots(dir)), report);
  const config = join(dir, "opencode.json");
  if (!(await exists(config))) {
    await writeFile(config, OPENCODE_PROJECT_CONFIG);
    report.push(`wrote ${config}`);
  } else if (!opencodeDeniesAm(await readFile(config, "utf8"))) {
    report.push(`check that ${config} contains "permission": {"skill": {"am": "deny"}}; otherwise opencode's model can invoke .agents/skills/am on its own`);
  }
  return report;
}

export async function uninstallGlobal(): Promise<string[]> {
  const report: string[] = [];
  const binLink = join(homedir(), ".local", "bin", "am");
  if ((await readlink(binLink).catch(() => undefined)) === BIN) {
    await unlink(binLink);
    report.push(`removed ${binLink}`);
  }
  for (const { path } of renderTargets("", globalRoots())) {
    if (await ownedByUs(path)) {
      await unlink(path);
      report.push(`removed ${path}`);
    }
  }
  return report.length ? report : ["no files created by am were found"];
}
