import { lstat, mkdir, readFile, readlink, symlink, unlink, writeFile } from "node:fs/promises";
import { homedir } from "node:os";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const BIN = fileURLToPath(new URL("../bin/am", import.meta.url));
const GUIDE = fileURLToPath(new URL("../skills/am/GUIDE.md", import.meta.url));

const DESCRIPTION =
  "Coordinate other coding agents (Claude Code, Codex, opencode) in tmux panes with the am CLI: start a helper, hand it a task, wait for it, read its reply.";

/** First line of every generated file; only files carrying it are ever overwritten or removed. */
const MARKER = "generated by `am install`";

export interface GeneratedFile {
  path: string;
  content: string;
}

// The guide is opt-in everywhere: each agent only gets it when the user invokes
// it explicitly (/am in Claude Code and opencode, $am in Codex).
export function renderTargets(guide: string, roots: { claude: string; codex: string; opencode: string }): GeneratedFile[] {
  const body = (request: string) => guide.replace("{{REQUEST}}", request).trim();
  const withArgs = body(" Their request: $ARGUMENTS");
  return [
    {
      // A command, not a skill directory: opencode also loads .claude/skills and ignores disable-model-invocation.
      path: join(roots.claude, "commands", "am.md"),
      content: `---\ndescription: ${JSON.stringify(DESCRIPTION)}\nargument-hint: <what to delegate>\ndisable-model-invocation: true\n---\n<!-- ${MARKER} -->\n\n${withArgs}\n`,
    },
    {
      path: join(roots.codex, "am", "SKILL.md"),
      content: `---\nname: am\ndescription: ${JSON.stringify(DESCRIPTION)}\n---\n<!-- ${MARKER} -->\n\n${body(" Their request is the message that invoked this skill.")}\n`,
    },
    {
      // Codex reads SKILL.md frontmatter keys name/description only; explicit-only lives here.
      path: join(roots.codex, "am", "agents", "openai.yaml"),
      content: `# ${MARKER}\npolicy:\n  allow_implicit_invocation: false\n`,
    },
    {
      path: join(roots.opencode, "commands", "am.md"),
      content: `---\ndescription: ${JSON.stringify(DESCRIPTION)}\n---\n<!-- ${MARKER} -->\n\n${withArgs}\n`,
    },
  ];
}

export function globalRoots() {
  const home = homedir();
  return {
    claude: join(home, ".claude"),
    // ~/.codex/skills rather than ~/.agents/skills: opencode scans the latter and would offer it to its model.
    codex: join(process.env.CODEX_HOME ?? join(home, ".codex"), "skills"),
    opencode: join(process.env.XDG_CONFIG_HOME ?? join(home, ".config"), "opencode"),
  };
}

export function projectRoots(dir: string) {
  return { claude: join(dir, ".claude"), codex: join(dir, ".agents", "skills"), opencode: join(dir, ".opencode") };
}

async function exists(path: string): Promise<boolean> {
  return lstat(path).then(
    () => true,
    () => false,
  );
}

async function ownedByUs(path: string): Promise<boolean> {
  return (await readFile(path, "utf8").catch(() => "")).includes(MARKER);
}

async function writeGenerated(files: GeneratedFile[], report: string[]): Promise<void> {
  for (const { path, content } of files) {
    if ((await exists(path)) && !(await ownedByUs(path))) {
      report.push(`跳过 ${path}（已有不是 am 生成的文件）`);
      continue;
    }
    if ((await readFile(path, "utf8").catch(() => undefined)) === content) {
      report.push(`已是最新 ${path}`);
      continue;
    }
    await mkdir(dirname(path), { recursive: true });
    await writeFile(path, content);
    report.push(`写入 ${path}`);
  }
}

export async function installGlobal(): Promise<string[]> {
  const report: string[] = [];
  const binLink = join(homedir(), ".local", "bin", "am");
  if (!(await exists(binLink))) {
    await mkdir(dirname(binLink), { recursive: true });
    await symlink(BIN, binLink);
    report.push(`链接 ${binLink} → ${BIN}`);
  } else {
    report.push((await readlink(binLink).catch(() => undefined)) === BIN ? `已存在 ${binLink}` : `跳过 ${binLink}（已被其他文件占用）`);
  }
  await writeGenerated(renderTargets(await readFile(GUIDE, "utf8"), globalRoots()), report);
  report.push("调用方式：Claude Code 和 opencode 输入 /am <要委派的事>，Codex 输入 $am <要委派的事>");
  return report;
}

/** opencode also loads .agents/skills, so a project opts its am skill out of opencode's model. */
export const OPENCODE_PROJECT_CONFIG = `${JSON.stringify({ $schema: "https://opencode.ai/config.json", permission: { skill: { am: "deny" } } }, null, 2)}\n`;

/** OpenCode's Wildcard.match (packages/opencode/src/util/wildcard.ts), including its trailing " *" rule. */
function wildcard(pattern: string, value: string): boolean {
  let escaped = pattern
    .replaceAll("\\", "/")
    .replace(/[.+^${}()|[\]\\]/g, "\\$&")
    .replace(/\*/g, ".*")
    .replace(/\?/g, ".");
  // "ls *" matches both "ls" and "ls -la".
  if (escaped.endsWith(" .*")) escaped = `${escaped.slice(0, -3)}( .*)?`;
  return new RegExp(`^${escaped}$`, "s").test(value.replaceAll("\\", "/"));
}

/** The action a rule (string, or object of patterns) gives `name`; the last matching pattern wins (config order, as OpenCode's evaluate()). */
function ruleAction(rule: unknown, name: string): string | undefined {
  if (typeof rule === "string") return rule;
  let action: string | undefined;
  if (rule && typeof rule === "object") {
    for (const [pattern, value] of Object.entries(rule)) if (typeof value === "string" && wildcard(pattern, name)) action = value;
  }
  return action;
}

/**
 * Whether an opencode.json keeps the am skill away from opencode's model:
 * the effective `skill` permission for "am" under opencode's rules (last
 * matching rule wins, top-level "*" included). Unparseable (e.g. JSONC) counts as no.
 */
export function opencodeDeniesAm(configText: string): boolean {
  let permission: unknown;
  try {
    permission = JSON.parse(configText)?.permission;
  } catch {
    return false;
  }
  let action: string | undefined;
  if (typeof permission === "string") action = permission;
  else if (permission && typeof permission === "object") {
    for (const [key, rule] of Object.entries(permission)) {
      if (!wildcard(key, "skill")) continue;
      action = ruleAction(rule, "am") ?? action;
    }
  }
  return action === "deny";
}

export async function installProject(dir: string): Promise<string[]> {
  const report: string[] = [];
  await writeGenerated(renderTargets(await readFile(GUIDE, "utf8"), projectRoots(dir)), report);
  const config = join(dir, "opencode.json");
  if (!(await exists(config))) {
    await writeFile(config, OPENCODE_PROJECT_CONFIG);
    report.push(`写入 ${config}`);
  } else if (!opencodeDeniesAm(await readFile(config, "utf8"))) {
    report.push(`请确认 ${config} 里有 "permission": {"skill": {"am": "deny"}}，否则 opencode 会自动调用 .agents/skills/am`);
  }
  return report;
}

export async function uninstallGlobal(): Promise<string[]> {
  const report: string[] = [];
  const binLink = join(homedir(), ".local", "bin", "am");
  if ((await readlink(binLink).catch(() => undefined)) === BIN) {
    await unlink(binLink);
    report.push(`已删除 ${binLink}`);
  }
  for (const { path } of renderTargets("", globalRoots())) {
    if (await ownedByUs(path)) {
      await unlink(path);
      report.push(`已删除 ${path}`);
    }
  }
  return report.length ? report : ["没有找到 am 创建的文件"];
}
